spring:
  application:
    name: spring-boot-GCP-Cloud-Spanner

  cloud:
    gcp:
      project-id: my-gcp-project
      spanner:
        instance-id: my-spanner-instance
        database: my-database

# No credentials here â€” ADC is used