spring:
  application:
    name: spring-boot-Gemini-AI
  ai:
    google:
      genai:
        project-id: <GIVE_PROJECT_ID_HERE>
        api-key: <GIVE_API_KEY_HERE>
        location: us-central1
        model:
          chat: google-genai

server:
  port: 9191

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.demo: DEBUG
  file:
    path: logs           # base log directory
    name: app.log        # main log file name