spring:
  application:
    name: spring-boot-Gemini-AI
  ai:
    google:
      genai:
        project-id: my-first-tech-project
        api-key: AIzaSyD28oPZwlRDbFERVWOWLkrssr7ZvvI6u8M
        location: us-central1
        model:
          chat: google-genai

server:
  port: 9191